// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: pow.proto

package pow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PowClient is the client API for Pow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PowClient interface {
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	CalculateFractional(ctx context.Context, in *CalculateFractionalRequest, opts ...grpc.CallOption) (*CalculateFractionalResponse, error)
}

type powClient struct {
	cc grpc.ClientConnInterface
}

func NewPowClient(cc grpc.ClientConnInterface) PowClient {
	return &powClient{cc}
}

func (c *powClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/pow.Pow/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powClient) CalculateFractional(ctx context.Context, in *CalculateFractionalRequest, opts ...grpc.CallOption) (*CalculateFractionalResponse, error) {
	out := new(CalculateFractionalResponse)
	err := c.cc.Invoke(ctx, "/pow.Pow/CalculateFractional", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowServer is the server API for Pow service.
// All implementations must embed UnimplementedPowServer
// for forward compatibility
type PowServer interface {
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	CalculateFractional(context.Context, *CalculateFractionalRequest) (*CalculateFractionalResponse, error)
	mustEmbedUnimplementedPowServer()
}

// UnimplementedPowServer must be embedded to have forward compatible implementations.
type UnimplementedPowServer struct {
}

func (UnimplementedPowServer) Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedPowServer) CalculateFractional(context.Context, *CalculateFractionalRequest) (*CalculateFractionalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFractional not implemented")
}
func (UnimplementedPowServer) mustEmbedUnimplementedPowServer() {}

// UnsafePowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowServer will
// result in compilation errors.
type UnsafePowServer interface {
	mustEmbedUnimplementedPowServer()
}

func RegisterPowServer(s grpc.ServiceRegistrar, srv PowServer) {
	s.RegisterService(&Pow_ServiceDesc, srv)
}

func _Pow_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pow.Pow/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pow_CalculateFractional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFractionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowServer).CalculateFractional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pow.Pow/CalculateFractional",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowServer).CalculateFractional(ctx, req.(*CalculateFractionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pow_ServiceDesc is the grpc.ServiceDesc for Pow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pow.Pow",
	HandlerType: (*PowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Pow_Calculate_Handler,
		},
		{
			MethodName: "CalculateFractional",
			Handler:    _Pow_CalculateFractional_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pow.proto",
}
