// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: sub.proto

package sub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubClient is the client API for Sub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubClient interface {
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	CalculateFractional(ctx context.Context, in *CalculateFractionalRequest, opts ...grpc.CallOption) (*CalculateFractionalResponse, error)
}

type subClient struct {
	cc grpc.ClientConnInterface
}

func NewSubClient(cc grpc.ClientConnInterface) SubClient {
	return &subClient{cc}
}

func (c *subClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/sub.Sub/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subClient) CalculateFractional(ctx context.Context, in *CalculateFractionalRequest, opts ...grpc.CallOption) (*CalculateFractionalResponse, error) {
	out := new(CalculateFractionalResponse)
	err := c.cc.Invoke(ctx, "/sub.Sub/CalculateFractional", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubServer is the server API for Sub service.
// All implementations must embed UnimplementedSubServer
// for forward compatibility
type SubServer interface {
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	CalculateFractional(context.Context, *CalculateFractionalRequest) (*CalculateFractionalResponse, error)
	mustEmbedUnimplementedSubServer()
}

// UnimplementedSubServer must be embedded to have forward compatible implementations.
type UnimplementedSubServer struct {
}

func (UnimplementedSubServer) Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedSubServer) CalculateFractional(context.Context, *CalculateFractionalRequest) (*CalculateFractionalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFractional not implemented")
}
func (UnimplementedSubServer) mustEmbedUnimplementedSubServer() {}

// UnsafeSubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubServer will
// result in compilation errors.
type UnsafeSubServer interface {
	mustEmbedUnimplementedSubServer()
}

func RegisterSubServer(s grpc.ServiceRegistrar, srv SubServer) {
	s.RegisterService(&Sub_ServiceDesc, srv)
}

func _Sub_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sub.Sub/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sub_CalculateFractional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFractionalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubServer).CalculateFractional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sub.Sub/CalculateFractional",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubServer).CalculateFractional(ctx, req.(*CalculateFractionalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sub_ServiceDesc is the grpc.ServiceDesc for Sub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sub.Sub",
	HandlerType: (*SubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Sub_Calculate_Handler,
		},
		{
			MethodName: "CalculateFractional",
			Handler:    _Sub_CalculateFractional_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sub.proto",
}
